In [3]:
name = "Adam"
friend_name = "Joshua"
best_food = "Pounded Yam and egusi soup"
friend_food ="Yam and egg sauce"
print ("My name is {} and my friend name is {}. My best food is {} and my friend`s best food is {}".format(name,friend_name,best_food,friend_food))

My name is Adam and my friend name is Joshua. My best food is Pounded Yam and egusi soup and my friend`s best food is Yam and egg sauce


In [ ]:
import numpy as np

In [38]:
np.array(num)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
num = [1,2,3,4,5,6,7,8,9,10]

In [41]:
type(num)

list

In [45]:
num = np.array(num)

In [64]:
type(num)

numpy.ndarray

In [69]:
much_list = [
    [1,2,3,4,5,6],
    [7,8,9,10,11,12],
    [13,14,15,16,17,18]
]


In [70]:
much_list_array = np.array(much_list)

In [71]:
much_list_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [77]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
max1 = np.random.randn(100)

In [90]:
np.max(max1)

np.float64(2.531606418574177)

In [93]:
np.random.randint(0,100, 7)

array([18, 94, 20, 28, 68, 44, 81], dtype=int32)

In [124]:
max = np.arange(0,52,2)

In [129]:
max.reshape(13,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38],
       [40, 42],
       [44, 46],
       [48, 50]])

In [160]:
max.argmax()

np.int64(25)

In [161]:
max

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [162]:
m = np.arange(2,10,3)

In [163]:
max.reshape(13,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38],
       [40, 42],
       [44, 46],
       [48, 50]])

In [20]:
import numpy as np

In [21]:
maxes = np.random.randint(0,50,2)

In [22]:
np.max(maxes)

np.int32(45)

In [24]:
maxes.argmax()

np.int64(0)

In [41]:
maxes= np.arange(2,1)

In [54]:
max= np.random.randn(9,7)

In [55]:
np.max(max)

np.float64(1.866137993220716)

In [56]:
max.argmax()

np.int64(49)

In [74]:
max = np.zeros(6)

In [72]:
max

array([0., 0., 0., 0., 0., 0.])

In [81]:
ma = np.eye(5)

In [105]:
np.argmin(7)

np.int64(0)

In [88]:
ma

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
ma.dtype

dtype('float64')

In [94]:
my_arrays = np.random.randint(0,100,9)

In [95]:
my_arrays

array([42, 57, 13, 78, 43, 25, 69, 54, 91], dtype=int32)

In [107]:
my_arrays[0:1]
print(my_arrays)

[42 57 13 78 43 25 69 54 91]


In [110]:
my_arrays[0:4] = 7
print(my_arrays)

[ 7  7  7  7  7 25 69 54 91]


In [111]:
arrays1 = np.arange(0,50)

In [112]:
arrays1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [116]:
arr = arrays1[0:51]

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [118]:
arr[0:45] = 100
print(arr)

[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100  45  46  47  48  49]


In [119]:
arrays1

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100,  45,  46,  47,  48,  49])

In [122]:
arrays3 = arr.copy()

In [123]:
arrays3

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100,  45,  46,  47,  48,  49])

In [124]:
arrays3[:] = 7

In [125]:
arrays3

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7])

In [149]:
arr4 = np.linspace(5,6)

In [150]:
arr4

array([5.        , 5.02040816, 5.04081633, 5.06122449, 5.08163265,
       5.10204082, 5.12244898, 5.14285714, 5.16326531, 5.18367347,
       5.20408163, 5.2244898 , 5.24489796, 5.26530612, 5.28571429,
       5.30612245, 5.32653061, 5.34693878, 5.36734694, 5.3877551 ,
       5.40816327, 5.42857143, 5.44897959, 5.46938776, 5.48979592,
       5.51020408, 5.53061224, 5.55102041, 5.57142857, 5.59183673,
       5.6122449 , 5.63265306, 5.65306122, 5.67346939, 5.69387755,
       5.71428571, 5.73469388, 5.75510204, 5.7755102 , 5.79591837,
       5.81632653, 5.83673469, 5.85714286, 5.87755102, 5.89795918,
       5.91836735, 5.93877551, 5.95918367, 5.97959184, 6.        ])

In [148]:
arr4.shape

(5, 6)

In [156]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [157]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
arr_2d[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [180]:
ar = np.arange(1,10)

In [181]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
arr2 = ar[ar > 5]

In [188]:
print(arr2)

[6 7 8 9]


In [201]:
ar+ 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

In [203]:
np.sqrt(ar)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [204]:
np.exp(ar)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [207]:
np.log(ar[8])

np.float64(2.1972245773362196)

In [209]:
ma = np.random.randn(4,7)

In [210]:
ma

array([[-0.86093324,  0.82596129,  1.34467782, -1.47602226, -0.27055573,
         1.22340234, -1.01751708],
       [ 1.48600479,  0.58460029,  0.42890277,  0.16998196, -1.24251664,
        -1.53048167, -0.99758246],
       [-0.20464617, -1.49701878, -0.91408123,  1.03745706,  0.45178192,
        -0.10727311,  0.85376784],
       [ 0.93692127, -0.24927463,  0.32714298, -1.31900715, -0.94685795,
         1.44316231, -0.62609747]])

In [208]:
import pandas as pd

In [212]:
df = pd.DataFrame(ma, index = ["a","b","c","d"], columns = ["a","b","c","d","e","f","g"])

In [213]:
df

,a,b,c,d,e,f,g
a,-0.860933,0.825961,1.344678,-1.476022,-0.270556,1.223402,-1.017517
b,1.486005,0.584600,0.428903,0.169982,-1.242517,-1.530482,-0.997582
c,-0.204646,-1.497019,-0.914081,1.037457,0.451782,-0.107273,0.853768
d,0.936921,-0.249275,0.327143,-1.319007,-0.946858,1.443162,-0.626097


In [222]:
series = pd.Series(data = np.arange(1,10), index = ["a", "b", "c", "d", "e", "f", "g", "h", "i"])

In [223]:
series

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64

In [221]:
series.shape

(9,)